# Documentation available at https://expeditor.chef.io/docs/getting-started/
rubygems:
 - inspec-vault

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: inspec-notify

github:
  delete_branch_on_merge: true
  major_bump_labels:
    - "CI/Bump Major Version"
  minor_bump_labels:
    - "CI/Bump Minor Version"
  version_tag_format: v{{version}}

changelog:
  categories:
    - "Type/New Feature": "New Features"
    - "Type/Enhancement": "Enhancements"
    - "Type/Bug": "Bug Fixes"
    - "Type/Chore": "Internal Improvements"
    - "Type/Tech Debt": "Internal Improvements"

pipelines:
 - verify:
    description: Pull Request validation tests
    public: false
 - integration:
    description: Run integration tests against a vault server locally
    public: false

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "CI/Skip Version Bump"
        - "CI/Skip All"
  - bash:.expeditor/update_version.sh:
      only_if: built_in:bump_version
  - built_in:update_changelog:
      ignore_labels:
        - "CI/Skip Changelog"
        - "CI/Skip All"
  - built_in:build_gem:
      only_if:
        - built_in:bump_version

promote:
  actions:
    - built_in:rollover_changelog
    - built_in:publish_rubygems
